stages:
  - test
  - lint


# Тестирование
test:
  stage: test
  image: python:3.11
  before_script:
    - cd app
  script:
    - pip install -r ../requirements.txt
    - python -m pytest test_calculator.py -v

# Проверка кодстайла
lint:
  stage: lint
  image: python:3.11
  before_script:
    - cd app
  script:
    - pip install -r ../requirements.txt
    - flake8 calculator.py test_calculator.py --max-line-length=120

