stages:
  - test
<<<<<<< HEAD
  - lint

test:
  stage: test
  image: python:3.11
  before_script:
    - cd app
  script:
    - pip install -r ../requirements.txt
    - python -m pytest test_calculator.py -v

lint:
  stage: lint
  image: python:3.11
  before_script:
    - cd app
  script:
    - pip install -r ../requirements.txt
    - flake8 calculator.py test_calculator.py --max-line-length=120
=======
  - build

variables:
  DEPLOY_DIR: "/var/www/finance_calculator"

test:
  stage: test
  image: python:3.10
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest test_finance_calculator.py -v
  only:
    - main

build:
  stage: build
  image: python:3.10
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - mkdir -p $DEPLOY_DIR
    - cp finance_calculator_gui.py $DEPLOY_DIR/
  only:
    - main
>>>>>>> 2feb373 (first commit)
